### ISSUE TITLE
Arquivo único

### ISSUE THREAD

**Issue by ericariello** [ericariello/Reativos#1]
Devemos ter um arquivo para o teste e outro para a "biblioteca" event_driven. (Tarefa3/parte1)

**Comment by fsantanna** [comment]
É recomendável. :)

**Comment by ericariello** [comment]
Resolvido com a criação de header file + event_driven.c + event_driven_test.ino (código usuário)

**Comment by ericariello** [comment]
Resolvido com a criação de header file + event_driven.c + event_driven_test.ino (código usuário)
